server:
  port: 8082

spring:
  application:
    name: consumer
  # RabbitMQ配置
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          # 重试初始间隔时间
          initial-interval: 3000ms
          multiplier: 2
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          # 重试初始间隔时间
          initial-interval: 3000ms
          multiplier: 2

# RabbitMQ交换机及队列名称配置
rabbitmq:
  simpleQueue:
    name: simpleQueue
  workQueue:
    name: workQueue
  publishSubscribe:
    name: publishSubscribeExchange
    queue1: publishSubscribeQueue1
    queue2: publishSubscribeQueue2
    queue3: publishSubscribeQueue3
  routing:
    name: routingExchange
    queue1: routingQueue1
    queueRoutingKey1:
    queue2: routingQueue2
    queueRoutingKey2: app
    queue3: routingQueue3
    queueRoutingKey3: pc
  topics:
    name: topicsExchange
    queue1: topicsQueue1
    queueRoutingKey1:
    queue2: topicsQueue2
    # 特殊字符转义
    queueRoutingKey2: "*"
    queue3: topicsQueue3
    # 特殊字符转义
    queueRoutingKey3: "#"
  ackQueue:
    name: ackQueue
  orderQueue:
    name: orderQueue
  deadLetterExchange:
    name: deadLetterExchange
    routingKey:
  deadLetterQueue:
    name: deadLetter