server:
  port: 8081

spring:
  application:
    name: producer
  # RabbitMQ配置
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 配置更新 https://blog.csdn.net/yaomingyang/article/details/108410286
    publisher-confirm-type: correlated
    publisher-returns: true


# RabbitMQ交换机及队列名称配置
rabbitmq:
  simpleQueue:
    name: simpleQueue
  workQueue:
    name: workQueue
  publishSubscribe:
    name: publishSubscribeExchange
  routing:
    name: routingExchange
    queueRoutingKey1:
    queueRoutingKey2: app
    queueRoutingKey3: pc
  topics:
    name: topicsExchange
  ackQueue:
    name: ackQueue
  orderQueue:
    name: orderQueue